#!/bin/sh

if echo "$@" | grep -qe --verify; then
	sed -e 's/#.\+$//' $0 | \
		grep -oe '-[em] [[:upper:]_]\+' | \
		sed -e 's/^-. //' | sort | uniq | sed -e 's/^/CONFIG_/' | \
	while read line; do
		grep -e "\\<${line}\\>" .config > /dev/null || echo ${line}
	done | sed -e '
		1iThese configs are not found in .config:
		s/^/- /'
	exit
fi

config \
	-e DEBUG_KERNEL \
	-e DEBUG_INFO \
	-e FRAME_POINTER \
	-e EXPERT \
	-e PROC_FS \
	-e SYSFS \
		-e KERNFS \
	-e IKCONFIG \
	-e IKCONFIG_PROC \
	-e KALLSYMS \
	|| exit

# KGDB
config \
	-e KGDB \
	-e TTY \
	-e VT \
		-e INPUT \
	-e HW_CONSOLE \
	-e KGDB_SERIAL_CONSOLE \
		-e CONSOLE_POLL \
		-e MAGIC_SYSRQ \
	-e KGDB_KDB \
	|| exit

# perf
config \
	-e PROFILING \
	-e PERF_EVENTS \
		-e IRQ_WORK \
		-e SRCU \
	|| exit

# kprobes, uprobes
config \
	-e MODULES \
	-e KPROBES \
		-e KALLSYMS \
	-e FTRACE \
	-e KPROBE_EVENTS \
		-e TRACING \
			-e RING_BUFFER \
				-e TRACE_CLOCK \
				-e IRQ_WORK \
			-e STACKTRACE \
			-e TRACEPOINTS \
			-e NOP_TRACER \
			-e BINARY_PRINTF \
			-e EVENT_TRACING \
				-e CONTEXT_SWITCH_TRACER \
				-e GLOB \
		-e PROBE_EVENTS \
		-e DYNAMIC_EVENTS \
	-e UPROBES \
	-e UPROBE_EVENTS \
	|| exit

# eBPF
config \
	-e BPF \
	-e BPF_SYSCALL \
	-e HAVE_EBPF_JIT \
	-e MODULES \
	-e BPF_JIT \
	-e BPF_EVENTS \
	-e IKHEADERS \
	-m NET_CLS_BPF \
	-m NET_ACT_BPF \
	|| exit
