#!/bin/sh

if echo "$@" | grep -qe --verify; then
	maybe_error=0
	trap 'maybe_error=1' USR1
	sed -e 's/#.\+$//' $0 | \
		grep -oe '-[em] [[:upper:]_]\+' | \
		sed -e 's/^-. //' | sort | uniq | sed -e 's/^/CONFIG_/' | \
	while read line; do
		grep -e "\\<${line}\\>" .config > /dev/null && continue
		echo ${line}
		kill -s USR1 $$
	done | sed -e '
		1iERROR. The following configs may not be applied to .config:
		s/^/- /'
	exit ${maybe_error}
fi

config \
	-e DEBUG_KERNEL \
	-e DEBUG_INFO \
	-e FRAME_POINTER \
	-e EXPERT \
	-e PROC_FS \
	-e SYSFS \
	-e IKCONFIG \
	-e IKCONFIG_PROC \
	-e KALLSYMS \
	|| exit

# KGDB
config \
	-e KGDB \
	-e TTY \
	-e VT \
	-e HW_CONSOLE \
	-e KGDB_SERIAL_CONSOLE \
	-e KGDB_KDB \
	|| exit

# perf
config \
	-e PROFILING \
	-e PERF_EVENTS \
	|| exit

# kprobes, uprobes
config \
	-e MODULES \
	-e KPROBES \
	-e FTRACE \
	-e KPROBE_EVENTS \
	-e PERF_EVENTS \
	-e UPROBE_EVENTS \
	|| exit

# eBPF
config \
	-e BPF \
	-e BPF_SYSCALL \
	-e MODULES \
	-e NET \
	-e BPF_JIT \
	-e KPROBES \
	-e FTRACE \
	-e KPROBE_EVENTS \
	-e UPROBE_EVENTS \
	-e PERF_EVENTS \
	-e BPF_EVENTS \
	-e SYSFS \
	-e IKHEADERS \
	-e NET_SCHED \
	-e NET_CLS_ACT \
	-m NET_CLS_BPF \
	-m NET_ACT_BPF \
	|| exit

# Ftrace
config \
	-e FTRACE \
	-e FUNCTION_TRACER \
	-e FUNCTION_GRAPH_TRACER \
	-e FTRACE_SYSCALLS \
	-e TRACER_SNAPSHOT \
	-e STACK_TRACER \
	-e DYNAMIC_FTRACE \
	|| exit

# Ftrace(additional)
config \
	-e IRQSOFF_TRACER \
	-e SCHED_TRACER \
	-e SYSFS \
	-e BLOCK \
	-e BLK_DEV_IO_TRACE \
	-e FUNCTION_PROFILER \
	|| exit
